/* -----------------------------------------------------
1. Show all customers
----------------------------------------------------- */
SELECT * FROM customers;


/* -----------------------------------------------------
2. Show all products
----------------------------------------------------- */
SELECT * FROM products;


/* -----------------------------------------------------
3. Show all orders
----------------------------------------------------- */
SELECT * FROM orders;


/* -----------------------------------------------------
4. Show customer name, product name, and quantity ordered
----------------------------------------------------- */
SELECT c.customer_name, p.product_name, o.quantity
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN products p
ON o.product_id = p.product_id;


/* -----------------------------------------------------
5. Calculate total revenue of the coffee shop
Revenue = price × quantity
----------------------------------------------------- */
SELECT SUM(p.price * o.quantity) AS total_revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id;


/* -----------------------------------------------------
6. Show total revenue generated by each product
----------------------------------------------------- */
SELECT p.product_name,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC;


/* -----------------------------------------------------
7. Show total quantity sold per product
----------------------------------------------------- */
SELECT p.product_name,
SUM(o.quantity) AS total_sold
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC;


/* -----------------------------------------------------
8. Find the most popular product
----------------------------------------------------- */
SELECT p.product_name,
SUM(o.quantity) AS total_sold
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sold DESC
LIMIT 1;


/* -----------------------------------------------------
9. Calculate total spending by each customer
----------------------------------------------------- */
SELECT c.customer_name,
SUM(p.price * o.quantity) AS total_spent
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY total_spent DESC;


/* -----------------------------------------------------
10. Find the top spending customer
----------------------------------------------------- */
SELECT c.customer_name,
SUM(p.price * o.quantity) AS total_spent
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.customer_name
ORDER BY total_spent DESC
LIMIT 1;


/* -----------------------------------------------------
11. Count the number of orders placed by each customer
----------------------------------------------------- */
SELECT c.customer_name,
COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name;


/* -----------------------------------------------------
12. Show number of orders from each city
----------------------------------------------------- */
SELECT c.city,
COUNT(o.order_id) AS total_orders
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
GROUP BY c.city;


/* -----------------------------------------------------
13. Calculate revenue generated from each city
----------------------------------------------------- */
SELECT c.city,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN products p
ON o.product_id = p.product_id
GROUP BY c.city
ORDER BY revenue DESC;


/* -----------------------------------------------------
14. Calculate average quantity ordered per product
----------------------------------------------------- */
SELECT p.product_name,
AVG(o.quantity) AS avg_quantity
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name;


/* -----------------------------------------------------
15. Show products that sold more than 2 units
----------------------------------------------------- */
SELECT p.product_name,
SUM(o.quantity) AS total_sold
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
HAVING total_sold > 2;


/* -----------------------------------------------------
16. Show number of orders per date
----------------------------------------------------- */
SELECT order_date,
COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_date;


/* -----------------------------------------------------
17. Calculate revenue generated per date
----------------------------------------------------- */
SELECT o.order_date,
SUM(p.price * o.quantity) AS revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY o.order_date;


/* -----------------------------------------------------
18. Find customers who never placed an order
----------------------------------------------------- */
SELECT c.customer_name
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;


/* -----------------------------------------------------
19. Find the most expensive product
----------------------------------------------------- */
SELECT product_name, price
FROM products
ORDER BY price DESC
LIMIT 1;


/* -----------------------------------------------------
20. Find the cheapest product
----------------------------------------------------- */
SELECT product_name, price
FROM products
ORDER BY price ASC
LIMIT 1;
